# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatecode',
            name='user',
            field=models.CharField(max_length=100, verbose_name='用户名'),
        ),
    ]
